// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bar.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBarItem = `-- name: AddBarItem :exec
INSERT INTO bar_items (user_id, ingredient_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddBarItemParams struct {
	UserID       uuid.UUID `json:"user_id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
}

func (q *Queries) AddBarItem(ctx context.Context, arg AddBarItemParams) error {
	_, err := q.db.Exec(ctx, addBarItem, arg.UserID, arg.IngredientID)
	return err
}

const listBarItems = `-- name: ListBarItems :many
SELECT b.created_at AS added_at, i.id, i.name, i.kind, i.parent_id, i.abv, i.description, i.created_by, i.created_at
FROM bar_items b
JOIN ingredients i ON i.id = b.ingredient_id
WHERE b.user_id = $1
ORDER BY i.kind, i.name
`

type ListBarItemsRow struct {
	AddedAt     pgtype.Timestamptz `json:"added_at"`
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Kind        IngredientKind     `json:"kind"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Abv         float64            `json:"abv"`
	Description *string            `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListBarItems(ctx context.Context, userID uuid.UUID) ([]ListBarItemsRow, error) {
	rows, err := q.db.Query(ctx, listBarItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarItemsRow
	for rows.Next() {
		var i ListBarItemsRow
		if err := rows.Scan(
			&i.AddedAt,
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.Abv,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBarItem = `-- name: RemoveBarItem :exec
DELETE FROM bar_items WHERE user_id = $1 AND ingredient_id = $2
`

type RemoveBarItemParams struct {
	UserID       uuid.UUID `json:"user_id"`
	IngredientID uuid.UUID `json:"ingredient_id"`
}

func (q *Queries) RemoveBarItem(ctx context.Context, arg RemoveBarItemParams) error {
	_, err := q.db.Exec(ctx, removeBarItem, arg.UserID, arg.IngredientID)
	return err
}
