// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drinks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDrinkByID = `-- name: GetDrinkByID :one
SELECT id, name, category, recipe_ingredients, recipe_instructions, created_at FROM drinks WHERE id = $1
`

func (q *Queries) GetDrinkByID(ctx context.Context, id uuid.UUID) (Drink, error) {
	row := q.db.QueryRow(ctx, getDrinkByID, id)
	var i Drink
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.RecipeIngredients,
		&i.RecipeInstructions,
		&i.CreatedAt,
	)
	return i, err
}

const listAllDrinks = `-- name: ListAllDrinks :many
SELECT id, name FROM drinks ORDER BY name
`

type ListAllDrinksRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListAllDrinks(ctx context.Context) ([]ListAllDrinksRow, error) {
	rows, err := q.db.Query(ctx, listAllDrinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDrinksRow
	for rows.Next() {
		var i ListAllDrinksRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDrinks = `-- name: SearchDrinks :many
SELECT d.id, d.name, d.category, d.recipe_ingredients, d.recipe_instructions, d.created_at,
       COALESCE(AVG(r.rating), 0)::float8 AS average_rating,
       COUNT(r.id)                        AS total_reviews
FROM drinks d
LEFT JOIN reviews r ON r.drink_id = d.id
WHERE d.name ILIKE $1 OR d.category ILIKE $1
GROUP BY d.id
ORDER BY d.name
`

type SearchDrinksRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Category           string             `json:"category"`
	RecipeIngredients  []string           `json:"recipe_ingredients"`
	RecipeInstructions *string            `json:"recipe_instructions"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	AverageRating      float64            `json:"average_rating"`
	TotalReviews       int64              `json:"total_reviews"`
}

func (q *Queries) SearchDrinks(ctx context.Context, pattern string) ([]SearchDrinksRow, error) {
	rows, err := q.db.Query(ctx, searchDrinks, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDrinksRow
	for rows.Next() {
		var i SearchDrinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.RecipeIngredients,
			&i.RecipeInstructions,
			&i.CreatedAt,
			&i.AverageRating,
			&i.TotalReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
