// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favourites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavourite = `-- name: AddFavourite :exec
INSERT INTO favourites (user_id, recipe_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavouriteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) AddFavourite(ctx context.Context, arg AddFavouriteParams) error {
	_, err := q.db.Exec(ctx, addFavourite, arg.UserID, arg.RecipeID)
	return err
}

const listFavourites = `-- name: ListFavourites :many
SELECT r.id, r.slug, r.name, r.description, r.instructions, r.method, r.glass, r.source, r.author_id, r.attribution, r.sweetness, r.est_abv, r.image_url, r.created_at, r.updated_at, r.parent_recipe_id, u.username AS author_name, g.name AS glass_name,
       pr.name AS parent_recipe_name,
       COALESCE(AVG(rv.rating), 0)::float8 AS average_rating,
       COUNT(rv.id)                        AS total_reviews,
       f.created_at                        AS favourited_at
FROM favourites f
JOIN recipes r        ON r.id = f.recipe_id
JOIN glass_types g    ON g.slug = r.glass
LEFT JOIN users u     ON u.id = r.author_id
LEFT JOIN recipes pr  ON pr.id = r.parent_recipe_id
LEFT JOIN reviews rv  ON rv.recipe_id = r.id
WHERE f.user_id = $1
GROUP BY r.id, u.username, g.name, pr.name, f.created_at
ORDER BY f.created_at DESC
`

type ListFavouritesRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	Instructions     *string            `json:"instructions"`
	Method           RecipeMethod       `json:"method"`
	Glass            string             `json:"glass"`
	Source           RecipeSource       `json:"source"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	Attribution      *string            `json:"attribution"`
	Sweetness        *int16             `json:"sweetness"`
	EstAbv           *float64           `json:"est_abv"`
	ImageUrl         *string            `json:"image_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ParentRecipeID   pgtype.UUID        `json:"parent_recipe_id"`
	AuthorName       *string            `json:"author_name"`
	GlassName        string             `json:"glass_name"`
	ParentRecipeName *string            `json:"parent_recipe_name"`
	AverageRating    float64            `json:"average_rating"`
	TotalReviews     int64              `json:"total_reviews"`
	FavouritedAt     pgtype.Timestamptz `json:"favourited_at"`
}

func (q *Queries) ListFavourites(ctx context.Context, userID uuid.UUID) ([]ListFavouritesRow, error) {
	rows, err := q.db.Query(ctx, listFavourites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavouritesRow
	for rows.Next() {
		var i ListFavouritesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Method,
			&i.Glass,
			&i.Source,
			&i.AuthorID,
			&i.Attribution,
			&i.Sweetness,
			&i.EstAbv,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentRecipeID,
			&i.AuthorName,
			&i.GlassName,
			&i.ParentRecipeName,
			&i.AverageRating,
			&i.TotalReviews,
			&i.FavouritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavourite = `-- name: RemoveFavourite :exec
DELETE FROM favourites WHERE user_id = $1 AND recipe_id = $2
`

type RemoveFavouriteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) RemoveFavourite(ctx context.Context, arg RemoveFavouriteParams) error {
	_, err := q.db.Exec(ctx, removeFavourite, arg.UserID, arg.RecipeID)
	return err
}
