// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const followingReviews = `-- name: FollowingReviews :many
SELECT rv.id, rv.rating, rv.comment, rv.impairment_level, rv.photo_url,
       rv.user_id, rv.created_at, r.name AS recipe_name, u.username
FROM reviews rv
JOIN recipes r ON r.id = rv.recipe_id
JOIN users u   ON u.id = rv.user_id
WHERE rv.user_id IN (SELECT followee_id FROM follows WHERE follower_id = $1)
ORDER BY rv.created_at DESC
`

type FollowingReviewsRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          *int16             `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RecipeName      string             `json:"recipe_name"`
	Username        string             `json:"username"`
}

func (q *Queries) FollowingReviews(ctx context.Context, followerID uuid.UUID) ([]FollowingReviewsRow, error) {
	rows, err := q.db.Query(ctx, followingReviews, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowingReviewsRow
	for rows.Next() {
		var i FollowingReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows WHERE follower_id = $1 AND followee_id = $2
)
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, u.profile_picture
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $1
ORDER BY f.created_at DESC
`

type ListFollowersRow struct {
	ID             uuid.UUID `json:"id"`
	Username       string    `json:"username"`
	ProfilePicture *string   `json:"profile_picture"`
}

func (q *Queries) ListFollowers(ctx context.Context, followeeID uuid.UUID) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.ProfilePicture); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, u.profile_picture
FROM follows f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
`

type ListFollowingRow struct {
	ID             uuid.UUID `json:"id"`
	Username       string    `json:"username"`
	ProfilePicture *string   `json:"profile_picture"`
}

func (q *Queries) ListFollowing(ctx context.Context, followerID uuid.UUID) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(&i.ID, &i.Username, &i.ProfilePicture); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}
