// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: glasses.sql

package sqlc

import (
	"context"
)

const listGlassTypes = `-- name: ListGlassTypes :many
SELECT slug, name, sort_order FROM glass_types ORDER BY sort_order, name
`

func (q *Queries) ListGlassTypes(ctx context.Context) ([]GlassType, error) {
	rows, err := q.db.Query(ctx, listGlassTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlassType
	for rows.Next() {
		var i GlassType
		if err := rows.Scan(&i.Slug, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
