// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, name, kind, parent_id, abv, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url
`

type CreateIngredientParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Kind        IngredientKind `json:"kind"`
	ParentID    pgtype.UUID    `json:"parent_id"`
	Abv         float64        `json:"abv"`
	Description *string        `json:"description"`
	CreatedBy   pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.ParentID,
		arg.Abv,
		arg.Description,
		arg.CreatedBy,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ParentID,
		&i.Abv,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Popularity,
		&i.ImageUrl,
	)
	return i, err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url FROM ingredients WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id uuid.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ParentID,
		&i.Abv,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Popularity,
		&i.ImageUrl,
	)
	return i, err
}

const getIngredientsByIDs = `-- name: GetIngredientsByIDs :many
SELECT id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url FROM ingredients WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetIngredientsByIDs(ctx context.Context, ids []uuid.UUID) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredientsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.Abv,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Popularity,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOfficialIngredientByName = `-- name: GetOfficialIngredientByName :one
SELECT id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url FROM ingredients
WHERE lower(name) = lower($1) AND created_by IS NULL
`

func (q *Queries) GetOfficialIngredientByName(ctx context.Context, name string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getOfficialIngredientByName, name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ParentID,
		&i.Abv,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Popularity,
		&i.ImageUrl,
	)
	return i, err
}

const listIngredientChildren = `-- name: ListIngredientChildren :many
SELECT id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url FROM ingredients
WHERE parent_id = $1
  AND (created_by IS NULL OR created_by = $2)
ORDER BY name
`

type ListIngredientChildrenParams struct {
	Parent pgtype.UUID `json:"parent"`
	Viewer pgtype.UUID `json:"viewer"`
}

// Brands/styles under one generic (Vodka -> Grey Goose, Tito's), alphabetical.
func (q *Queries) ListIngredientChildren(ctx context.Context, arg ListIngredientChildrenParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredientChildren, arg.Parent, arg.Viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.Abv,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Popularity,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelIngredients = `-- name: ListTopLevelIngredients :many
SELECT id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url FROM ingredients
WHERE parent_id IS NULL
  AND (created_by IS NULL OR created_by = $1)
  AND ($2::ingredient_kind IS NULL OR kind = $2)
ORDER BY popularity DESC, name
`

type ListTopLevelIngredientsParams struct {
	Viewer pgtype.UUID     `json:"viewer"`
	Kind   *IngredientKind `json:"kind"`
}

// Top-level generics for the add-to-bar browse grid: the official catalogue plus
// the viewer's own root ingredients, optionally filtered by kind, most common first.
func (q *Queries) ListTopLevelIngredients(ctx context.Context, arg ListTopLevelIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listTopLevelIngredients, arg.Viewer, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.Abv,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Popularity,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT code, name, abbrev, kind, ml_equiv FROM units ORDER BY kind, code
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Abbrev,
			&i.Kind,
			&i.MlEquiv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url FROM ingredients
WHERE (created_by IS NULL OR created_by = $1)
  AND name ILIKE $2
  AND ($3::ingredient_kind IS NULL OR kind = $3)
ORDER BY popularity DESC, name
LIMIT 50
`

type SearchIngredientsParams struct {
	Viewer  pgtype.UUID     `json:"viewer"`
	Pattern string          `json:"pattern"`
	Kind    *IngredientKind `json:"kind"`
}

// Catalogue search for pickers: everyone sees the official catalogue, plus
// their own custom ingredients.
func (q *Queries) SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, searchIngredients, arg.Viewer, arg.Pattern, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.Abv,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Popularity,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIngredientParent = `-- name: SetIngredientParent :exec
UPDATE ingredients SET parent_id = $2 WHERE id = $1
`

type SetIngredientParentParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) SetIngredientParent(ctx context.Context, arg SetIngredientParentParams) error {
	_, err := q.db.Exec(ctx, setIngredientParent, arg.ID, arg.ParentID)
	return err
}

const upsertOfficialIngredient = `-- name: UpsertOfficialIngredient :one
INSERT INTO ingredients (id, name, kind, abv, description, popularity, image_url, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULL)
ON CONFLICT (lower(name)) WHERE created_by IS NULL
DO UPDATE SET kind        = EXCLUDED.kind,
              abv         = EXCLUDED.abv,
              description = COALESCE(EXCLUDED.description, ingredients.description),
              popularity  = EXCLUDED.popularity,
              image_url   = COALESCE(EXCLUDED.image_url, ingredients.image_url)
RETURNING id, name, kind, parent_id, abv, description, created_by, created_at, popularity, image_url
`

type UpsertOfficialIngredientParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Kind        IngredientKind `json:"kind"`
	Abv         float64        `json:"abv"`
	Description *string        `json:"description"`
	Popularity  int32          `json:"popularity"`
	ImageUrl    *string        `json:"image_url"`
}

// Seeder upsert: official catalogue rows keyed by case-insensitive name.
// Parents are resolved in a second pass via SetIngredientParent.
func (q *Queries) UpsertOfficialIngredient(ctx context.Context, arg UpsertOfficialIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, upsertOfficialIngredient,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Abv,
		arg.Description,
		arg.Popularity,
		arg.ImageUrl,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ParentID,
		&i.Abv,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Popularity,
		&i.ImageUrl,
	)
	return i, err
}
