// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: makeable.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const makeableRecipes = `-- name: MakeableRecipes :many
WITH RECURSIVE bar_expanded AS (
    SELECT i.id, i.parent_id
    FROM bar_items b
    JOIN ingredients i ON i.id = b.ingredient_id
    WHERE b.user_id = $1
    UNION
    SELECT p.id, p.parent_id
    FROM ingredients p
    JOIN bar_expanded c ON c.parent_id = p.id
)
SELECT r.id, r.slug, r.name, r.description, r.instructions, r.method, r.glass, r.source, r.author_id, r.attribution, r.sweetness, r.est_abv, r.image_url, r.created_at, r.updated_at, r.parent_recipe_id, u.username AS author_name, g.name AS glass_name,
       pr.name AS parent_recipe_name,
       COALESCE(AVG(rv.rating), 0)::float8 AS average_rating,
       COUNT(rv.id)                        AS total_reviews
FROM recipes r
JOIN glass_types g    ON g.slug = r.glass
LEFT JOIN users u     ON u.id = r.author_id
LEFT JOIN recipes pr  ON pr.id = r.parent_recipe_id
LEFT JOIN reviews rv  ON rv.recipe_id = r.id
WHERE EXISTS (
          SELECT 1 FROM recipe_ingredients ri WHERE ri.recipe_id = r.id
      )
  AND NOT EXISTS (
          SELECT 1 FROM recipe_ingredients ri
          WHERE ri.recipe_id = r.id
            AND NOT ri.is_optional
            AND ri.ingredient_id NOT IN (SELECT id FROM bar_expanded)
      )
GROUP BY r.id, u.username, g.name, pr.name
ORDER BY total_reviews DESC, average_rating DESC, r.name
LIMIT 100
`

type MakeableRecipesRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	Instructions     *string            `json:"instructions"`
	Method           RecipeMethod       `json:"method"`
	Glass            string             `json:"glass"`
	Source           RecipeSource       `json:"source"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	Attribution      *string            `json:"attribution"`
	Sweetness        *int16             `json:"sweetness"`
	EstAbv           *float64           `json:"est_abv"`
	ImageUrl         *string            `json:"image_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ParentRecipeID   pgtype.UUID        `json:"parent_recipe_id"`
	AuthorName       *string            `json:"author_name"`
	GlassName        string             `json:"glass_name"`
	ParentRecipeName *string            `json:"parent_recipe_name"`
	AverageRating    float64            `json:"average_rating"`
	TotalReviews     int64              `json:"total_reviews"`
}

// "My Menu": popular recipes the user can make from their bar.
//
// bar_expanded is the user's bar plus every ancestor of each bottle, so owning
// "Grey Goose" satisfies a recipe line that asks for plain "vodka". A recipe
// qualifies when every required (non-optional) line is covered.
// Ranking is popularity for now; AI-assisted ranking can re-order later.
func (q *Queries) MakeableRecipes(ctx context.Context, userID uuid.UUID) ([]MakeableRecipesRow, error) {
	rows, err := q.db.Query(ctx, makeableRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MakeableRecipesRow
	for rows.Next() {
		var i MakeableRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Method,
			&i.Glass,
			&i.Source,
			&i.AuthorID,
			&i.Attribution,
			&i.Sweetness,
			&i.EstAbv,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentRecipeID,
			&i.AuthorName,
			&i.GlassName,
			&i.ParentRecipeName,
			&i.AverageRating,
			&i.TotalReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
