// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMenuItem = `-- name: AddMenuItem :exec
INSERT INTO menu_items (menu_id, recipe_id, position, note)
VALUES (
    $1, $2,
    COALESCE((SELECT MAX(position) + 1 FROM menu_items WHERE menu_id = $1), 0),
    $3
)
ON CONFLICT (menu_id, recipe_id) DO UPDATE SET note = EXCLUDED.note
`

type AddMenuItemParams struct {
	MenuID   uuid.UUID `json:"menu_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
	Note     *string   `json:"note"`
}

// Append a single recipe to the end of a menu (POST /menus/{id}/items).
func (q *Queries) AddMenuItem(ctx context.Context, arg AddMenuItemParams) error {
	_, err := q.db.Exec(ctx, addMenuItem, arg.MenuID, arg.RecipeID, arg.Note)
	return err
}

const createMenu = `-- name: CreateMenu :one

INSERT INTO menus (id, user_id, name, description, visibility, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, visibility, image_url, created_at, updated_at
`

type CreateMenuParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Visibility  MenuVisibility `json:"visibility"`
	ImageUrl    *string        `json:"image_url"`
}

// Menus: user-created lists of cocktails (public or private). Distinct from the
// computed makeable-from-bar feature (see makeable.sql).
//
// recipe_count and tag arrays come from correlated subqueries (each COALESCEd to
// a non-null value) so they compose cleanly without join fan-out.
func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.ImageUrl,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMenu = `-- name: DeleteMenu :execrows
DELETE FROM menus WHERE id = $1 AND user_id = $2
`

type DeleteMenuParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMenu(ctx context.Context, arg DeleteMenuParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMenu, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMenuItem = `-- name: DeleteMenuItem :execrows
DELETE FROM menu_items WHERE menu_id = $1 AND recipe_id = $2
`

type DeleteMenuItemParams struct {
	MenuID   uuid.UUID `json:"menu_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMenuItem, arg.MenuID, arg.RecipeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMenuItems = `-- name: DeleteMenuItems :exec
DELETE FROM menu_items WHERE menu_id = $1
`

// Full replace path (used on menu update): clear then re-insert with positions.
func (q *Queries) DeleteMenuItems(ctx context.Context, menuID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItems, menuID)
	return err
}

const getMenuByID = `-- name: GetMenuByID :one
SELECT m.id, m.user_id, m.name, m.description, m.visibility, m.image_url, m.created_at, m.updated_at, u.username AS author_name,
       COALESCE((SELECT COUNT(*) FROM menu_items mi WHERE mi.menu_id = m.id), 0)::bigint AS recipe_count,
       COALESCE((SELECT array_agg(t.slug  ORDER BY t.label)
                 FROM menu_tags mt JOIN tags t ON t.id = mt.tag_id
                 WHERE mt.menu_id = m.id), ARRAY[]::text[]) AS tag_slugs,
       COALESCE((SELECT array_agg(t.label ORDER BY t.label)
                 FROM menu_tags mt JOIN tags t ON t.id = mt.tag_id
                 WHERE mt.menu_id = m.id), ARRAY[]::text[]) AS tag_labels
FROM menus m
JOIN users u ON u.id = m.user_id
WHERE m.id = $1
`

type GetMenuByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Visibility  MenuVisibility     `json:"visibility"`
	ImageUrl    *string            `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  string             `json:"author_name"`
	RecipeCount int64              `json:"recipe_count"`
	TagSlugs    []string           `json:"tag_slugs"`
	TagLabels   []string           `json:"tag_labels"`
}

func (q *Queries) GetMenuByID(ctx context.Context, id uuid.UUID) (GetMenuByIDRow, error) {
	row := q.db.QueryRow(ctx, getMenuByID, id)
	var i GetMenuByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.RecipeCount,
		&i.TagSlugs,
		&i.TagLabels,
	)
	return i, err
}

const insertMenuItem = `-- name: InsertMenuItem :exec
INSERT INTO menu_items (menu_id, recipe_id, position, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (menu_id, recipe_id) DO UPDATE SET position = EXCLUDED.position, note = EXCLUDED.note
`

type InsertMenuItemParams struct {
	MenuID   uuid.UUID `json:"menu_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
	Position int16     `json:"position"`
	Note     *string   `json:"note"`
}

func (q *Queries) InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) error {
	_, err := q.db.Exec(ctx, insertMenuItem,
		arg.MenuID,
		arg.RecipeID,
		arg.Position,
		arg.Note,
	)
	return err
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT r.id, r.slug, r.name, r.description, r.instructions, r.method, r.glass, r.source, r.author_id, r.attribution, r.sweetness, r.est_abv, r.image_url, r.created_at, r.updated_at, r.parent_recipe_id, u.username AS author_name, g.name AS glass_name, pr.name AS parent_recipe_name,
       COALESCE(AVG(rv.rating), 0)::float8 AS average_rating,
       COUNT(rv.id)                        AS total_reviews,
       mi.position, mi.note
FROM menu_items mi
JOIN recipes r       ON r.id = mi.recipe_id
JOIN glass_types g   ON g.slug = r.glass
LEFT JOIN users u    ON u.id = r.author_id
LEFT JOIN recipes pr ON pr.id = r.parent_recipe_id
LEFT JOIN reviews rv ON rv.recipe_id = r.id
WHERE mi.menu_id = $1
GROUP BY r.id, u.username, g.name, pr.name, mi.position, mi.note
ORDER BY mi.position
`

type ListMenuItemsRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	Instructions     *string            `json:"instructions"`
	Method           RecipeMethod       `json:"method"`
	Glass            string             `json:"glass"`
	Source           RecipeSource       `json:"source"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	Attribution      *string            `json:"attribution"`
	Sweetness        *int16             `json:"sweetness"`
	EstAbv           *float64           `json:"est_abv"`
	ImageUrl         *string            `json:"image_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ParentRecipeID   pgtype.UUID        `json:"parent_recipe_id"`
	AuthorName       *string            `json:"author_name"`
	GlassName        string             `json:"glass_name"`
	ParentRecipeName *string            `json:"parent_recipe_name"`
	AverageRating    float64            `json:"average_rating"`
	TotalReviews     int64              `json:"total_reviews"`
	Position         int16              `json:"position"`
	Note             *string            `json:"note"`
}

// Recipes in a menu, in display order. Same recipe summary columns as the other
// recipe list queries, plus the line's position and note.
func (q *Queries) ListMenuItems(ctx context.Context, menuID uuid.UUID) ([]ListMenuItemsRow, error) {
	rows, err := q.db.Query(ctx, listMenuItems, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemsRow
	for rows.Next() {
		var i ListMenuItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Method,
			&i.Glass,
			&i.Source,
			&i.AuthorID,
			&i.Attribution,
			&i.Sweetness,
			&i.EstAbv,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentRecipeID,
			&i.AuthorName,
			&i.GlassName,
			&i.ParentRecipeName,
			&i.AverageRating,
			&i.TotalReviews,
			&i.Position,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusByUser = `-- name: ListMenusByUser :many
SELECT m.id, m.user_id, m.name, m.description, m.visibility, m.image_url, m.created_at, m.updated_at, u.username AS author_name,
       COALESCE((SELECT COUNT(*) FROM menu_items mi WHERE mi.menu_id = m.id), 0)::bigint AS recipe_count,
       COALESCE((SELECT array_agg(t.slug  ORDER BY t.label)
                 FROM menu_tags mt JOIN tags t ON t.id = mt.tag_id
                 WHERE mt.menu_id = m.id), ARRAY[]::text[]) AS tag_slugs,
       COALESCE((SELECT array_agg(t.label ORDER BY t.label)
                 FROM menu_tags mt JOIN tags t ON t.id = mt.tag_id
                 WHERE mt.menu_id = m.id), ARRAY[]::text[]) AS tag_labels
FROM menus m
JOIN users u ON u.id = m.user_id
WHERE m.user_id = $1
  AND ($2::bool OR m.visibility = 'public')
ORDER BY m.updated_at DESC
`

type ListMenusByUserParams struct {
	Owner          uuid.UUID `json:"owner"`
	IncludePrivate bool      `json:"include_private"`
}

type ListMenusByUserRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Visibility  MenuVisibility     `json:"visibility"`
	ImageUrl    *string            `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  string             `json:"author_name"`
	RecipeCount int64              `json:"recipe_count"`
	TagSlugs    []string           `json:"tag_slugs"`
	TagLabels   []string           `json:"tag_labels"`
}

// A user's own menus. include_private is true only when the viewer is the owner;
// otherwise only the public ones are returned.
func (q *Queries) ListMenusByUser(ctx context.Context, arg ListMenusByUserParams) ([]ListMenusByUserRow, error) {
	rows, err := q.db.Query(ctx, listMenusByUser, arg.Owner, arg.IncludePrivate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenusByUserRow
	for rows.Next() {
		var i ListMenusByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.RecipeCount,
			&i.TagSlugs,
			&i.TagLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMenus = `-- name: SearchMenus :many
SELECT m.id, m.user_id, m.name, m.description, m.visibility, m.image_url, m.created_at, m.updated_at, u.username AS author_name,
       COALESCE((SELECT COUNT(*) FROM menu_items mi WHERE mi.menu_id = m.id), 0)::bigint AS recipe_count,
       COALESCE((SELECT array_agg(t.slug  ORDER BY t.label)
                 FROM menu_tags mt JOIN tags t ON t.id = mt.tag_id
                 WHERE mt.menu_id = m.id), ARRAY[]::text[]) AS tag_slugs,
       COALESCE((SELECT array_agg(t.label ORDER BY t.label)
                 FROM menu_tags mt JOIN tags t ON t.id = mt.tag_id
                 WHERE mt.menu_id = m.id), ARRAY[]::text[]) AS tag_labels,
       COALESCE(
         CASE WHEN $1::text = '' THEN 0
              ELSE ts_rank(
                     setweight(to_tsvector('english', m.name), 'A') ||
                     setweight(to_tsvector('english', coalesce(m.description, '')), 'B'),
                     websearch_to_tsquery('english', $1::text))
                   + similarity(m.name, $1::text)
         END, 0)::float8 AS rank
FROM menus m
JOIN users u ON u.id = m.user_id
WHERE m.visibility = 'public'
  AND (
        $1::text = ''
        OR to_tsvector('english', m.name || ' ' || coalesce(m.description, '')) @@ websearch_to_tsquery('english', $1::text)
        OR m.name % $1::text
        OR EXISTS (SELECT 1 FROM menu_tags mt2 JOIN tags t2 ON t2.id = mt2.tag_id
                   WHERE mt2.menu_id = m.id AND (t2.slug = $1::text OR t2.label ILIKE '%' || $1::text || '%'))
      )
  AND ($2::text IS NULL OR EXISTS (
          SELECT 1 FROM menu_tags mt3 JOIN tags t3 ON t3.id = mt3.tag_id
          WHERE mt3.menu_id = m.id AND t3.slug = $2))
ORDER BY rank DESC, recipe_count DESC, m.updated_at DESC
LIMIT $3
`

type SearchMenusParams struct {
	Query string  `json:"query"`
	Tag   *string `json:"tag"`
	Lim   int64   `json:"lim"`
}

type SearchMenusRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Visibility  MenuVisibility     `json:"visibility"`
	ImageUrl    *string            `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  string             `json:"author_name"`
	RecipeCount int64              `json:"recipe_count"`
	TagSlugs    []string           `json:"tag_slugs"`
	TagLabels   []string           `json:"tag_labels"`
	Rank        float64            `json:"rank"`
}

// Public-menu discovery: full-text + fuzzy (pg_trgm) + tag match, same shape as
// SearchRecipes. An empty query ranks everything 0 and falls back to recency.
func (q *Queries) SearchMenus(ctx context.Context, arg SearchMenusParams) ([]SearchMenusRow, error) {
	rows, err := q.db.Query(ctx, searchMenus, arg.Query, arg.Tag, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMenusRow
	for rows.Next() {
		var i SearchMenusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.RecipeCount,
			&i.TagSlugs,
			&i.TagLabels,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menus
SET name        = $1,
    description = $2,
    visibility  = $3,
    image_url   = $4
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, name, description, visibility, image_url, created_at, updated_at
`

type UpdateMenuParams struct {
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Visibility  MenuVisibility `json:"visibility"`
	ImageUrl    *string        `json:"image_url"`
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
}

// Only the owner may edit. A miss (wrong owner or unknown id) returns zero rows,
// which the handler treats as "not found", mirroring UpdateRecipe.
func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, updateMenu,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.ImageUrl,
		arg.ID,
		arg.UserID,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
