// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Drink struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Category           string             `json:"category"`
	RecipeIngredients  []string           `json:"recipe_ingredients"`
	RecipeInstructions *string            `json:"recipe_instructions"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Follow struct {
	FollowerID uuid.UUID          `json:"follower_id"`
	FolloweeID uuid.UUID          `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DrinkID         uuid.UUID          `json:"drink_id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	ProfilePicture *string            `json:"profile_picture"`
	Location       *string            `json:"location"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserDrinkPreference struct {
	UserID    uuid.UUID          `json:"user_id"`
	DrinkID   uuid.UUID          `json:"drink_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
