// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addUserDrinkPreference = `-- name: AddUserDrinkPreference :exec
INSERT INTO user_drink_preferences (user_id, drink_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserDrinkPreferenceParams struct {
	UserID  uuid.UUID `json:"user_id"`
	DrinkID uuid.UUID `json:"drink_id"`
}

func (q *Queries) AddUserDrinkPreference(ctx context.Context, arg AddUserDrinkPreferenceParams) error {
	_, err := q.db.Exec(ctx, addUserDrinkPreference, arg.UserID, arg.DrinkID)
	return err
}

const clearUserDrinkPreferences = `-- name: ClearUserDrinkPreferences :exec
DELETE FROM user_drink_preferences WHERE user_id = $1
`

func (q *Queries) ClearUserDrinkPreferences(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserDrinkPreferences, userID)
	return err
}

const listUserDrinkPreferences = `-- name: ListUserDrinkPreferences :many
SELECT d.name
FROM user_drink_preferences p
JOIN drinks d ON d.id = p.drink_id
WHERE p.user_id = $1
ORDER BY d.name
`

func (q *Queries) ListUserDrinkPreferences(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserDrinkPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
