// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (id, slug, name, description, instructions, method, glass,
                     source, author_id, attribution, sweetness, est_abv, image_url,
                     parent_recipe_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, slug, name, description, instructions, method, glass, source, author_id, attribution, sweetness, est_abv, image_url, created_at, updated_at, parent_recipe_id
`

type CreateRecipeParams struct {
	ID             uuid.UUID    `json:"id"`
	Slug           string       `json:"slug"`
	Name           string       `json:"name"`
	Description    *string      `json:"description"`
	Instructions   *string      `json:"instructions"`
	Method         RecipeMethod `json:"method"`
	Glass          string       `json:"glass"`
	Source         RecipeSource `json:"source"`
	AuthorID       pgtype.UUID  `json:"author_id"`
	Attribution    *string      `json:"attribution"`
	Sweetness      *int16       `json:"sweetness"`
	EstAbv         *float64     `json:"est_abv"`
	ImageUrl       *string      `json:"image_url"`
	ParentRecipeID pgtype.UUID  `json:"parent_recipe_id"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Method,
		arg.Glass,
		arg.Source,
		arg.AuthorID,
		arg.Attribution,
		arg.Sweetness,
		arg.EstAbv,
		arg.ImageUrl,
		arg.ParentRecipeID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Method,
		&i.Glass,
		&i.Source,
		&i.AuthorID,
		&i.Attribution,
		&i.Sweetness,
		&i.EstAbv,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentRecipeID,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes
WHERE id = $1 AND author_id = $2 AND source = 'community'
`

type DeleteRecipeParams struct {
	ID       uuid.UUID   `json:"id"`
	AuthorID pgtype.UUID `json:"author_id"`
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipe, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipeIngredients = `-- name: DeleteRecipeIngredients :exec
DELETE FROM recipe_ingredients WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeIngredients(ctx context.Context, recipeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipeIngredients, recipeID)
	return err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT r.id, r.slug, r.name, r.description, r.instructions, r.method, r.glass, r.source, r.author_id, r.attribution, r.sweetness, r.est_abv, r.image_url, r.created_at, r.updated_at, r.parent_recipe_id, u.username AS author_name, g.name AS glass_name,
       pr.name AS parent_recipe_name,
       COALESCE(AVG(rv.rating), 0)::float8 AS average_rating,
       COUNT(rv.id)                        AS total_reviews
FROM recipes r
JOIN glass_types g    ON g.slug = r.glass
LEFT JOIN users u     ON u.id = r.author_id
LEFT JOIN recipes pr  ON pr.id = r.parent_recipe_id
LEFT JOIN reviews rv  ON rv.recipe_id = r.id
WHERE r.id = $1
GROUP BY r.id, u.username, g.name, pr.name
`

type GetRecipeByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	Instructions     *string            `json:"instructions"`
	Method           RecipeMethod       `json:"method"`
	Glass            string             `json:"glass"`
	Source           RecipeSource       `json:"source"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	Attribution      *string            `json:"attribution"`
	Sweetness        *int16             `json:"sweetness"`
	EstAbv           *float64           `json:"est_abv"`
	ImageUrl         *string            `json:"image_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ParentRecipeID   pgtype.UUID        `json:"parent_recipe_id"`
	AuthorName       *string            `json:"author_name"`
	GlassName        string             `json:"glass_name"`
	ParentRecipeName *string            `json:"parent_recipe_name"`
	AverageRating    float64            `json:"average_rating"`
	TotalReviews     int64              `json:"total_reviews"`
}

func (q *Queries) GetRecipeByID(ctx context.Context, id uuid.UUID) (GetRecipeByIDRow, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i GetRecipeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Method,
		&i.Glass,
		&i.Source,
		&i.AuthorID,
		&i.Attribution,
		&i.Sweetness,
		&i.EstAbv,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentRecipeID,
		&i.AuthorName,
		&i.GlassName,
		&i.ParentRecipeName,
		&i.AverageRating,
		&i.TotalReviews,
	)
	return i, err
}

const insertRecipeIngredient = `-- name: InsertRecipeIngredient :exec
INSERT INTO recipe_ingredients (recipe_id, position, ingredient_id, amount, unit_code, note, is_optional, is_garnish)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRecipeIngredientParams struct {
	RecipeID     uuid.UUID `json:"recipe_id"`
	Position     int16     `json:"position"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	Amount       *float64  `json:"amount"`
	UnitCode     *string   `json:"unit_code"`
	Note         *string   `json:"note"`
	IsOptional   bool      `json:"is_optional"`
	IsGarnish    bool      `json:"is_garnish"`
}

func (q *Queries) InsertRecipeIngredient(ctx context.Context, arg InsertRecipeIngredientParams) error {
	_, err := q.db.Exec(ctx, insertRecipeIngredient,
		arg.RecipeID,
		arg.Position,
		arg.IngredientID,
		arg.Amount,
		arg.UnitCode,
		arg.Note,
		arg.IsOptional,
		arg.IsGarnish,
	)
	return err
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT ri.position, ri.amount, ri.unit_code, ri.note, ri.is_optional, ri.is_garnish,
       un.name AS unit_name, un.abbrev AS unit_abbrev, un.kind AS unit_kind, un.ml_equiv,
       i.id AS ingredient_id, i.name AS ingredient_name,
       i.kind AS ingredient_kind, i.abv
FROM recipe_ingredients ri
JOIN ingredients i ON i.id = ri.ingredient_id
LEFT JOIN units un ON un.code = ri.unit_code
WHERE ri.recipe_id = $1
ORDER BY ri.position
`

type ListRecipeIngredientsRow struct {
	Position       int16          `json:"position"`
	Amount         *float64       `json:"amount"`
	UnitCode       *string        `json:"unit_code"`
	Note           *string        `json:"note"`
	IsOptional     bool           `json:"is_optional"`
	IsGarnish      bool           `json:"is_garnish"`
	UnitName       *string        `json:"unit_name"`
	UnitAbbrev     *string        `json:"unit_abbrev"`
	UnitKind       *UnitKind      `json:"unit_kind"`
	MlEquiv        *float64       `json:"ml_equiv"`
	IngredientID   uuid.UUID      `json:"ingredient_id"`
	IngredientName string         `json:"ingredient_name"`
	IngredientKind IngredientKind `json:"ingredient_kind"`
	Abv            float64        `json:"abv"`
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID uuid.UUID) ([]ListRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeIngredientsRow
	for rows.Next() {
		var i ListRecipeIngredientsRow
		if err := rows.Scan(
			&i.Position,
			&i.Amount,
			&i.UnitCode,
			&i.Note,
			&i.IsOptional,
			&i.IsGarnish,
			&i.UnitName,
			&i.UnitAbbrev,
			&i.UnitKind,
			&i.MlEquiv,
			&i.IngredientID,
			&i.IngredientName,
			&i.IngredientKind,
			&i.Abv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipes = `-- name: SearchRecipes :many
SELECT r.id, r.slug, r.name, r.description, r.instructions, r.method, r.glass, r.source, r.author_id, r.attribution, r.sweetness, r.est_abv, r.image_url, r.created_at, r.updated_at, r.parent_recipe_id, u.username AS author_name, g.name AS glass_name,
       pr.name AS parent_recipe_name,
       COALESCE(AVG(rv.rating), 0)::float8 AS average_rating,
       COUNT(rv.id)                        AS total_reviews,
       COALESCE((SELECT array_agg(t.slug  ORDER BY t.label)
                 FROM recipe_tags rt JOIN tags t ON t.id = rt.tag_id
                 WHERE rt.recipe_id = r.id), ARRAY[]::text[]) AS tag_slugs,
       COALESCE((SELECT array_agg(t.label ORDER BY t.label)
                 FROM recipe_tags rt JOIN tags t ON t.id = rt.tag_id
                 WHERE rt.recipe_id = r.id), ARRAY[]::text[]) AS tag_labels,
       COALESCE(
         CASE WHEN $1::text = '' THEN 0
              ELSE ts_rank(
                     setweight(to_tsvector('english', r.name), 'A') ||
                     setweight(to_tsvector('english', coalesce(r.description, '')), 'B'),
                     websearch_to_tsquery('english', $1::text))
                   + similarity(r.name, $1::text)
         END, 0)::float8 AS rank
FROM recipes r
JOIN glass_types g    ON g.slug = r.glass
LEFT JOIN users u     ON u.id = r.author_id
LEFT JOIN recipes pr  ON pr.id = r.parent_recipe_id
LEFT JOIN reviews rv  ON rv.recipe_id = r.id
WHERE (
        $1::text = ''
        OR to_tsvector('english', r.name || ' ' || coalesce(r.description, '')) @@ websearch_to_tsquery('english', $1::text)
        OR r.name % $1::text
        OR EXISTS (SELECT 1 FROM recipe_tags rt2 JOIN tags t2 ON t2.id = rt2.tag_id
                   WHERE rt2.recipe_id = r.id AND (t2.slug = $1::text OR t2.label ILIKE '%' || $1::text || '%'))
      )
  AND ($2::recipe_source IS NULL OR r.source = $2)
  AND ($3::float8 IS NULL OR r.est_abv <= $3)
  AND ($4::text IS NULL OR EXISTS (
          SELECT 1 FROM recipe_tags rt3 JOIN tags t3 ON t3.id = rt3.tag_id
          WHERE rt3.recipe_id = r.id AND t3.slug = $4))
GROUP BY r.id, u.username, g.name, pr.name
ORDER BY rank DESC, total_reviews DESC, average_rating DESC, r.name
LIMIT $5
`

type SearchRecipesParams struct {
	Query  string        `json:"query"`
	Source *RecipeSource `json:"source"`
	MaxAbv *float64      `json:"max_abv"`
	Tag    *string       `json:"tag"`
	Lim    int64         `json:"lim"`
}

type SearchRecipesRow struct {
	ID               uuid.UUID          `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	Instructions     *string            `json:"instructions"`
	Method           RecipeMethod       `json:"method"`
	Glass            string             `json:"glass"`
	Source           RecipeSource       `json:"source"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	Attribution      *string            `json:"attribution"`
	Sweetness        *int16             `json:"sweetness"`
	EstAbv           *float64           `json:"est_abv"`
	ImageUrl         *string            `json:"image_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ParentRecipeID   pgtype.UUID        `json:"parent_recipe_id"`
	AuthorName       *string            `json:"author_name"`
	GlassName        string             `json:"glass_name"`
	ParentRecipeName *string            `json:"parent_recipe_name"`
	AverageRating    float64            `json:"average_rating"`
	TotalReviews     int64              `json:"total_reviews"`
	TagSlugs         []string           `json:"tag_slugs"`
	TagLabels        []string           `json:"tag_labels"`
	Rank             float64            `json:"rank"`
}

// Ranked, typo-tolerant recipe search; also powers the popularity-ordered browse
// list when the query is empty (every row ranks 0 and falls back to popularity).
// Relevance combines full-text (name^A, description^B) with pg_trgm name
// similarity; an empty query short-circuits the match. Tags are matched in the
// WHERE and surfaced via correlated subqueries so they never inflate the review
// aggregates. Optional source / maxAbv / tag filters narrow the result.
func (q *Queries) SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]SearchRecipesRow, error) {
	rows, err := q.db.Query(ctx, searchRecipes,
		arg.Query,
		arg.Source,
		arg.MaxAbv,
		arg.Tag,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRecipesRow
	for rows.Next() {
		var i SearchRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Method,
			&i.Glass,
			&i.Source,
			&i.AuthorID,
			&i.Attribution,
			&i.Sweetness,
			&i.EstAbv,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentRecipeID,
			&i.AuthorName,
			&i.GlassName,
			&i.ParentRecipeName,
			&i.AverageRating,
			&i.TotalReviews,
			&i.TagSlugs,
			&i.TagLabels,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET name         = $1,
    description  = $2,
    instructions = $3,
    method       = $4,
    glass        = $5,
    sweetness    = $6,
    est_abv      = $7,
    image_url    = $8
WHERE id = $9 AND author_id = $10 AND source = 'community'
RETURNING id, slug, name, description, instructions, method, glass, source, author_id, attribution, sweetness, est_abv, image_url, created_at, updated_at, parent_recipe_id
`

type UpdateRecipeParams struct {
	Name         string       `json:"name"`
	Description  *string      `json:"description"`
	Instructions *string      `json:"instructions"`
	Method       RecipeMethod `json:"method"`
	Glass        string       `json:"glass"`
	Sweetness    *int16       `json:"sweetness"`
	EstAbv       *float64     `json:"est_abv"`
	ImageUrl     *string      `json:"image_url"`
	ID           uuid.UUID    `json:"id"`
	AuthorID     pgtype.UUID  `json:"author_id"`
}

// Only the author may edit, and only community recipes are editable via the API
// (official ones are managed by the seeder).
func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Method,
		arg.Glass,
		arg.Sweetness,
		arg.EstAbv,
		arg.ImageUrl,
		arg.ID,
		arg.AuthorID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Method,
		&i.Glass,
		&i.Source,
		&i.AuthorID,
		&i.Attribution,
		&i.Sweetness,
		&i.EstAbv,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentRecipeID,
	)
	return i, err
}

const upsertRecipeBySlug = `-- name: UpsertRecipeBySlug :one
INSERT INTO recipes (id, slug, name, description, instructions, method, glass,
                     source, author_id, attribution, sweetness, est_abv, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'official', NULL, $8, $9, $10, $11)
ON CONFLICT (slug)
DO UPDATE SET name         = EXCLUDED.name,
              description  = EXCLUDED.description,
              instructions = EXCLUDED.instructions,
              method       = EXCLUDED.method,
              glass        = EXCLUDED.glass,
              source       = 'official',
              attribution  = EXCLUDED.attribution,
              sweetness    = EXCLUDED.sweetness,
              est_abv      = EXCLUDED.est_abv,
              image_url    = EXCLUDED.image_url
RETURNING id, slug, name, description, instructions, method, glass, source, author_id, attribution, sweetness, est_abv, image_url, created_at, updated_at, parent_recipe_id
`

type UpsertRecipeBySlugParams struct {
	ID           uuid.UUID    `json:"id"`
	Slug         string       `json:"slug"`
	Name         string       `json:"name"`
	Description  *string      `json:"description"`
	Instructions *string      `json:"instructions"`
	Method       RecipeMethod `json:"method"`
	Glass        string       `json:"glass"`
	Attribution  *string      `json:"attribution"`
	Sweetness    *int16       `json:"sweetness"`
	EstAbv       *float64     `json:"est_abv"`
	ImageUrl     *string      `json:"image_url"`
}

// Seeder upsert: official recipes keyed by slug so re-running the importer
// updates in place.
func (q *Queries) UpsertRecipeBySlug(ctx context.Context, arg UpsertRecipeBySlugParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, upsertRecipeBySlug,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Method,
		arg.Glass,
		arg.Attribution,
		arg.Sweetness,
		arg.EstAbv,
		arg.ImageUrl,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Method,
		&i.Glass,
		&i.Source,
		&i.AuthorID,
		&i.Attribution,
		&i.Sweetness,
		&i.EstAbv,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentRecipeID,
	)
	return i, err
}
