// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, user_id, drink_id, rating, comment, impairment_level, photo_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, drink_id, rating, comment, impairment_level, photo_url, created_at
`

type CreateReviewParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	DrinkID         uuid.UUID `json:"drink_id"`
	Rating          int16     `json:"rating"`
	Comment         *string   `json:"comment"`
	ImpairmentLevel *int16    `json:"impairment_level"`
	PhotoUrl        *string   `json:"photo_url"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.UserID,
		arg.DrinkID,
		arg.Rating,
		arg.Comment,
		arg.ImpairmentLevel,
		arg.PhotoUrl,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DrinkID,
		&i.Rating,
		&i.Comment,
		&i.ImpairmentLevel,
		&i.PhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT r.id, r.rating, r.comment, r.impairment_level, r.photo_url,
       r.user_id, r.created_at, d.name AS drink_name, u.username
FROM reviews r
JOIN drinks d ON d.id = r.drink_id
JOIN users u ON u.id = r.user_id
ORDER BY r.created_at DESC
`

type ListReviewsRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DrinkName       string             `json:"drink_name"`
	Username        string             `json:"username"`
}

func (q *Queries) ListReviews(ctx context.Context) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.DrinkName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByDrink = `-- name: ListReviewsByDrink :many
SELECT r.id, r.rating, r.comment, r.impairment_level, r.photo_url,
       r.user_id, r.created_at, d.name AS drink_name, u.username
FROM reviews r
JOIN drinks d ON d.id = r.drink_id
JOIN users u ON u.id = r.user_id
WHERE r.drink_id = $1
ORDER BY r.created_at DESC
`

type ListReviewsByDrinkRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DrinkName       string             `json:"drink_name"`
	Username        string             `json:"username"`
}

func (q *Queries) ListReviewsByDrink(ctx context.Context, drinkID uuid.UUID) ([]ListReviewsByDrinkRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByDrink, drinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByDrinkRow
	for rows.Next() {
		var i ListReviewsByDrinkRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.DrinkName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT r.id, r.rating, r.comment, r.impairment_level, r.photo_url,
       r.user_id, r.created_at, d.name AS drink_name, u.username
FROM reviews r
JOIN drinks d ON d.id = r.drink_id
JOIN users u ON u.id = r.user_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
`

type ListReviewsByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DrinkName       string             `json:"drink_name"`
	Username        string             `json:"username"`
}

func (q *Queries) ListReviewsByUser(ctx context.Context, userID uuid.UUID) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByUserRow
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.DrinkName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostReviewedDrinks = `-- name: MostReviewedDrinks :many
SELECT d.id, d.name, d.category, d.recipe_ingredients, d.recipe_instructions,
       d.created_at, COUNT(r.id) AS total_reviews
FROM drinks d
JOIN reviews r ON r.drink_id = d.id
GROUP BY d.id
ORDER BY total_reviews DESC
LIMIT 5
`

type MostReviewedDrinksRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Category           string             `json:"category"`
	RecipeIngredients  []string           `json:"recipe_ingredients"`
	RecipeInstructions *string            `json:"recipe_instructions"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TotalReviews       int64              `json:"total_reviews"`
}

func (q *Queries) MostReviewedDrinks(ctx context.Context) ([]MostReviewedDrinksRow, error) {
	rows, err := q.db.Query(ctx, mostReviewedDrinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MostReviewedDrinksRow
	for rows.Next() {
		var i MostReviewedDrinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.RecipeIngredients,
			&i.RecipeInstructions,
			&i.CreatedAt,
			&i.TotalReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
