// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, user_id, recipe_id, rating, comment, impairment_level, photo_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, recipe_id, rating, comment, impairment_level, photo_url, created_at
`

type CreateReviewParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	RecipeID        uuid.UUID `json:"recipe_id"`
	Rating          int16     `json:"rating"`
	Comment         *string   `json:"comment"`
	ImpairmentLevel *int16    `json:"impairment_level"`
	PhotoUrl        *string   `json:"photo_url"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ID,
		arg.UserID,
		arg.RecipeID,
		arg.Rating,
		arg.Comment,
		arg.ImpairmentLevel,
		arg.PhotoUrl,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipeID,
		&i.Rating,
		&i.Comment,
		&i.ImpairmentLevel,
		&i.PhotoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT rv.id, rv.rating, rv.comment, rv.impairment_level, rv.photo_url,
       rv.user_id, rv.created_at, r.name AS recipe_name, u.username
FROM reviews rv
JOIN recipes r ON r.id = rv.recipe_id
JOIN users u   ON u.id = rv.user_id
ORDER BY rv.created_at DESC
`

type ListReviewsRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RecipeName      string             `json:"recipe_name"`
	Username        string             `json:"username"`
}

func (q *Queries) ListReviews(ctx context.Context) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsRow
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByRecipe = `-- name: ListReviewsByRecipe :many
SELECT rv.id, rv.rating, rv.comment, rv.impairment_level, rv.photo_url,
       rv.user_id, rv.created_at, r.name AS recipe_name, u.username
FROM reviews rv
JOIN recipes r ON r.id = rv.recipe_id
JOIN users u   ON u.id = rv.user_id
WHERE rv.recipe_id = $1
ORDER BY rv.created_at DESC
`

type ListReviewsByRecipeRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RecipeName      string             `json:"recipe_name"`
	Username        string             `json:"username"`
}

func (q *Queries) ListReviewsByRecipe(ctx context.Context, recipeID uuid.UUID) ([]ListReviewsByRecipeRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByRecipeRow
	for rows.Next() {
		var i ListReviewsByRecipeRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT rv.id, rv.rating, rv.comment, rv.impairment_level, rv.photo_url,
       rv.user_id, rv.created_at, r.name AS recipe_name, u.username
FROM reviews rv
JOIN recipes r ON r.id = rv.recipe_id
JOIN users u   ON u.id = rv.user_id
WHERE rv.user_id = $1
ORDER BY rv.created_at DESC
`

type ListReviewsByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Rating          int16              `json:"rating"`
	Comment         *string            `json:"comment"`
	ImpairmentLevel *int16             `json:"impairment_level"`
	PhotoUrl        *string            `json:"photo_url"`
	UserID          uuid.UUID          `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RecipeName      string             `json:"recipe_name"`
	Username        string             `json:"username"`
}

func (q *Queries) ListReviewsByUser(ctx context.Context, userID uuid.UUID) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByUserRow
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.ImpairmentLevel,
			&i.PhotoUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.RecipeName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
