// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteMenuTags = `-- name: DeleteMenuTags :exec
DELETE FROM menu_tags WHERE menu_id = $1
`

func (q *Queries) DeleteMenuTags(ctx context.Context, menuID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuTags, menuID)
	return err
}

const deleteRecipeTags = `-- name: DeleteRecipeTags :exec
DELETE FROM recipe_tags WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeTags(ctx context.Context, recipeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipeTags, recipeID)
	return err
}

const insertMenuTag = `-- name: InsertMenuTag :exec
INSERT INTO menu_tags (menu_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertMenuTagParams struct {
	MenuID uuid.UUID `json:"menu_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) InsertMenuTag(ctx context.Context, arg InsertMenuTagParams) error {
	_, err := q.db.Exec(ctx, insertMenuTag, arg.MenuID, arg.TagID)
	return err
}

const insertRecipeTag = `-- name: InsertRecipeTag :exec
INSERT INTO recipe_tags (recipe_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertRecipeTagParams struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) InsertRecipeTag(ctx context.Context, arg InsertRecipeTagParams) error {
	_, err := q.db.Exec(ctx, insertRecipeTag, arg.RecipeID, arg.TagID)
	return err
}

const listMenuTags = `-- name: ListMenuTags :many
SELECT t.id, t.slug, t.label, t.created_at FROM tags t
JOIN menu_tags mt ON mt.tag_id = t.id
WHERE mt.menu_id = $1
ORDER BY t.label
`

func (q *Queries) ListMenuTags(ctx context.Context, menuID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listMenuTags, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeTags = `-- name: ListRecipeTags :many
SELECT t.id, t.slug, t.label, t.created_at FROM tags t
JOIN recipe_tags rt ON rt.tag_id = t.id
WHERE rt.recipe_id = $1
ORDER BY t.label
`

func (q *Queries) ListRecipeTags(ctx context.Context, recipeID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listRecipeTags, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT id, slug, label, created_at FROM tags
WHERE slug LIKE $1 || '%'
   OR label ILIKE '%' || $1 || '%'
ORDER BY label
LIMIT 20
`

// Tag autocomplete: prefix match on slug, plus a looser substring match on label.
func (q *Queries) SearchTags(ctx context.Context, prefix *string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTags, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one

INSERT INTO tags (id, slug, label)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET label = tags.label
RETURNING id, slug, label, created_at
`

type UpsertTagParams struct {
	ID    uuid.UUID `json:"id"`
	Slug  string    `json:"slug"`
	Label string    `json:"label"`
}

// Tags: one shared, free-form pool keyed by a normalized slug. Recipes and menus
// both reference tags through their respective join tables.
// Idempotent insert keyed by slug. The no-op DO UPDATE guarantees RETURNING
// always yields the row (whether freshly inserted or pre-existing), and keeps the
// original label rather than clobbering it with later casing.
func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.ID, arg.Slug, arg.Label)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}
