// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.Location,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.Bio,
		&i.UpdatedAt,
		&i.MeasurePref,
	)
	return i, err
}

const deleteStaleUnverifiedUsers = `-- name: DeleteStaleUnverifiedUsers :execrows
DELETE FROM users
WHERE verified_at IS NULL AND created_at < $1
`

// Cleanup: drop unverified accounts whose verification window has long passed,
// freeing their username/email. Cascades remove any dependent rows.
func (q *Queries) DeleteStaleUnverifiedUsers(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleUnverifiedUsers, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.Location,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.Bio,
		&i.UpdatedAt,
		&i.MeasurePref,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.Location,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.Bio,
		&i.UpdatedAt,
		&i.MeasurePref,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.Location,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.Bio,
		&i.UpdatedAt,
		&i.MeasurePref,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref FROM users
WHERE $1::text = ''
   OR username ILIKE '%' || $1::text || '%'
   OR display_name ILIKE '%' || $1::text || '%'
   OR username % $1::text
ORDER BY similarity(username, $1::text) DESC, username
LIMIT $2
`

type SearchUsersParams struct {
	Query string `json:"query"`
	Lim   int64  `json:"lim"`
}

// Ranked, typo-tolerant user search over username and display_name. An empty
// query lists everyone alphabetically (similarity to ” is 0 for all rows).
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.ProfilePicture,
			&i.Location,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.DisplayName,
			&i.Bio,
			&i.UpdatedAt,
			&i.MeasurePref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topUsers = `-- name: TopUsers :many
SELECT u.id, u.username, u.email, u.password_hash, u.profile_picture, u.location, u.created_at, u.verified_at, u.display_name, u.bio, u.updated_at, u.measure_pref, COUNT(f.follower_id) AS follower_count
FROM users u
LEFT JOIN follows f ON f.followee_id = u.id
GROUP BY u.id
ORDER BY follower_count DESC, u.username
LIMIT 5
`

type TopUsersRow struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	ProfilePicture *string            `json:"profile_picture"`
	Location       *string            `json:"location"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	DisplayName    *string            `json:"display_name"`
	Bio            *string            `json:"bio"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	MeasurePref    MeasurePref        `json:"measure_pref"`
	FollowerCount  int64              `json:"follower_count"`
}

func (q *Queries) TopUsers(ctx context.Context) ([]TopUsersRow, error) {
	rows, err := q.db.Query(ctx, topUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopUsersRow
	for rows.Next() {
		var i TopUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.ProfilePicture,
			&i.Location,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.DisplayName,
			&i.Bio,
			&i.UpdatedAt,
			&i.MeasurePref,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnverifiedUserCredentials = `-- name: UpdateUnverifiedUserCredentials :one
UPDATE users
SET username = $1, password_hash = $2
WHERE id = $3 AND verified_at IS NULL
RETURNING id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref
`

type UpdateUnverifiedUserCredentialsParams struct {
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

// Re-registration: overwrite an as-yet-unverified account's credentials so the
// email's rightful owner can claim it. The verified_at guard makes this affect
// zero rows for already-verified accounts.
func (q *Queries) UpdateUnverifiedUserCredentials(ctx context.Context, arg UpdateUnverifiedUserCredentialsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUnverifiedUserCredentials, arg.Username, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.Location,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.Bio,
		&i.UpdatedAt,
		&i.MeasurePref,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username        = COALESCE($1, username),
    display_name    = COALESCE($2, display_name),
    bio             = COALESCE($3, bio),
    profile_picture = COALESCE($4, profile_picture),
    measure_pref    = COALESCE($5, measure_pref)
WHERE id = $6
RETURNING id, username, email, password_hash, profile_picture, location, created_at, verified_at, display_name, bio, updated_at, measure_pref
`

type UpdateUserParams struct {
	Username       *string      `json:"username"`
	DisplayName    *string      `json:"display_name"`
	Bio            *string      `json:"bio"`
	ProfilePicture *string      `json:"profile_picture"`
	MeasurePref    *MeasurePref `json:"measure_pref"`
	ID             uuid.UUID    `json:"id"`
}

// Updates the mutable profile fields. email is permanent after signup, but
// username may be changed (e.g. during account setup) subject to a
// uniqueness check performed by the caller. updated_at is maintained by the
// users_set_updated_at trigger.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.ProfilePicture,
		arg.MeasurePref,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.Location,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.Bio,
		&i.UpdatedAt,
		&i.MeasurePref,
	)
	return i, err
}
